### ISSUE TITLE
Matriz de adjacencia não está printando corretamente

### ISSUE THREAD

**Issue by azledev** [OrdemDEEV/ProjetoGrafos#1]
estou com um problema e gostaria de ajuda, na parte da matriz de adjacencia, ela simplesmente ignora os vértices conectados quando chega para comprar os vértices no vetor 2 HELP shsh

**Comment by azledev** [comment]
Vou usar lista duplamente encadeada para ver se resolve

**Comment by Eduardo555** [comment]
ok vamos ver isso ai cara
