### ISSUE TITLE
Vocês perceberam um erro no item 4 do menu? o de mostrar matriz de incidencia?

### ISSUE THREAD

**Issue by Eduardo555** [OrdemDEEV/ProjetoGrafos#2]
o erro foi causado agora ou ja estava la?

**Comment by azledev** [comment]
Sim, kkkk, eu nem tinha visto este issue, e resolvi este erro...

Aconteceu que eu estava tentando arrumar a interface de visualizar e começo a dar esse erro na hora da matriz de incidencia, (eu fiz umas besteira la), porem ja resolvi tudo, e agora a interface visualizar está fazendo umas coisas bem interessantes.

O erro tinha sido causado agora a pouco mesmo shsh.

**Comment by Eduardo555** [comment]
Ok
